# fly.toml app configuration file generated for remix-vite-cold-pine-2477 on 2024-07-29T22:58:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remix-vite-cold-pine-2477'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 512

[experimental]
auto_rollback = true

[build]
dockerfile = '/other/Dockerfile'
ignorefile = '/other/Dockerfile.dockerignore'

[[mounts]]
source = 'data'
destination = '/data'

[[services]]
protocol = 'tcp'
internal_port = 3000
processes = ['app']

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
type = 'requests'
hard_limit = 120
soft_limit = 80

[[services.http_checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/api/healthcheck"
protocol = "http"
timeout = "2s"
tls_skip_verify = false
headers = {}

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
