# fly.toml app configuration file generated for remix-vite-cold-pine-2477 on 2024-07-29T22:58:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remix-vite-cold-pine-2477'
primary_region = 'ams'
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 512

[build]
  dockerfile = "/other/Dockerfile"
  ignorefile = "/other/Dockerfile.dockerignore"

[mounts]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 80
    hard_limit = 120

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/api/healthcheck"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false
  headers = {}
